# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - mealsuggestionsapi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      
      - name: Create firebase config file
        uses: ttd2089/secret-file-action@1.0.0
        with:
          secret: ${{secrets.ADMINCONFIG}}
          output: ./src/config/adminConfig.json
#         uses: frdrwrt/write-to-file@v1.3
#         with:
#           filepath: ./src/config/adminConfig.json
#           content: ${{secrets.ADMINCONFIG}}

      - name: npm build and install
        uses: Jaid/action-npm-install@v1.2.4
        with:
          nodeEnv: production
          packageManager: npm

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: meals-api
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'mealsuggestionsapi'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C6F210429C13464A955838BCFFE6432F }}
          package: .
